server:
  port: 8761  

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: eurekamsvc.azurewebsites.net
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/
