server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: eurekamsvc.azurewebsites.net  # Dominio público de Azure
    prefer-ip-address: false  # Usar el nombre de host en lugar de la IP
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://eurekamsvc.azurewebsites.net/eureka/
